name: flutter_translation_sheet
description: Flutter Translation Sheet (fts) is a simple tool to help you with
  localization (l10n) generating json, arb and dart files.
version: 1.0.32
maintainer: Rodrigo López (@roipeker)
homepage: https://github.com/roipeker/flutter_translation_sheet
repository: https://github.com/roipeker/flutter_translation_sheet/
issue_tracker: https://github.com/roipeker/flutter_translation_sheet/issues

executables:
  fts: main

environment:
  sdk: ^3.1.0

dependencies:
  args: ^2.4.2
  collection: ^1.18.0
  dcli: ^4.0.1-alpha.11
  googleapis: ^11.4.0
  googleapis_auth: ^1.4.1
  io: ^1.0.4
  http: ^1.1.2
  path: ^1.8.3
  recase: ^4.1.0
  watcher: ^1.1.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.1.1